---
dependency:
  name: galaxy
  enabled: False

driver:
  name: docker

platforms:
  - name: ansible-role-fsviewer-debian-10
    image: debian:10
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ansible-role-fsviewer-debian-11
    image: debian:11
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ansible-role-fsviewer-ubuntu-1804
    image: ubuntu:18.04
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ansible-role-fsviewer-ubuntu-2004
    image: ubuntu:20.04
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

lint: |
    yamllint .
    ansible-lint
    flake8

provisioner:
  name: ansible

verifier:
  name: testinfra
