---
dependency:
  name: galaxy
  enabled: false

driver:
  name: docker

platforms:
  - name: ansible-role-fsviewer-debian-11
    image: debian:11
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ansible-role-fsviewer-debian-12
    image: debian:12
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ansible-role-fsviewer-ubuntu-2004
    image: ubuntu:20.04
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ansible-role-fsviewer-ubuntu-2204
    image: ubuntu:22.04
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible

verifier:
  name: testinfra
