---
- name: Prepare
  hosts: all

  tasks:
    - name: Ensure xvfb is installed
      ansible.builtin.apt:
        name: xvfb
        state: present
        update_cache: true

    - name: Ensure xfvb is running
      ansible.builtin.shell: "/usr/bin/Xvfb :99 -screen 0 1920x1080x24 -nolisten unix &"
      changed_when: false
